**Least Cost Path Assignment**

**Important instructions**

- Read the notes **LeastCostPathInRectangularGrid.pdf** file carefully. I spent a lot of time writing these. Understanding what is contained in these notes is critical to getting on top of this assignment.

- There is also a **video** that goes over the dynamic programming approach in an example. If you are confused about how dynamic programming is supposed to work, **watch the video.**

- When asked to provide a function, your code will be tested on examples and so it is important that you follow the specifications exactly.

    - the **input** parameters should have the types specified 
    - the **outputs** should have the types specified


- As usual, when asked to provide a function or literal assignments, these should be done in the cells provided.

- Make sure to remove the ellpses "..." when giving your answers.

- Make sure to not to delete the comment in the first line of a cell that says

    Code cell for Problem X

or

    Literal assignment cell for Problem X

- Your literal assignments should be **literal assignments**.

In [31]:
import numpy as np
import pandas as pd
from sympy.utilities.iterables import multiset_permutations

**Sympy**

We will use the **sympy** package to since it allows us to generate all possible permutations of the elements of a list. The list can consist of identical values, hence the term *multiset*. As you are hopefully all aware, the number of permutations of aaabb is Binomal(5,3) = 10.

In [32]:
perms=multiset_permutations(["a","a","a","b","b"])
for p in perms:
    print(p)

['a', 'a', 'a', 'b', 'b']
['a', 'a', 'b', 'a', 'b']
['a', 'a', 'b', 'b', 'a']
['a', 'b', 'a', 'a', 'b']
['a', 'b', 'a', 'b', 'a']
['a', 'b', 'b', 'a', 'a']
['b', 'a', 'a', 'a', 'b']
['b', 'a', 'a', 'b', 'a']
['b', 'a', 'b', 'a', 'a']
['b', 'b', 'a', 'a', 'a']


**Saving and Loading Numpy Arrays**

H and V arrays for sample problems have been created for you to download. These arrays are created using a numpy random number generator. The numpy **save** command is used to save the files. Whatever file name haS been used as an argument, by default the suffix *".npy"*  is appended to the file name, and the file is saved in a format that can be rea using **in any platform** using the numpy **load** command.

In the code below several numpy arrays are loaded. **You should not modify these arrays anywhere in the notebook.**

You will need 

- download the 10 files
- run the following code 

in order to store these arrays for use in the assignment.

**Be careful not to over-write these with your own arrays!!!**

In [33]:
H1=np.load("H1.npy")
V1=np.load("V1.npy")
print(H1)
print("\n")
print(V1)
H2=np.load("H2.npy")
V2=np.load("V2.npy")
H3=np.load("H3.npy")
V3=np.load("V3.npy")
H4=np.load("H4.npy")
V4=np.load("V4.npy")
H5=np.load("H5.npy")
V5=np.load("V5.npy")

[[0.44955589 0.83942522 0.92080801]
 [0.36959879 0.39579135 0.09652546]
 [0.07761471 0.21342692 0.77828452]
 [0.43522011 0.1701762  0.92285193]
 [0.04969842 0.9164841  0.03735467]]


[[0.36568341 0.95579184 0.44995062 0.22592981]
 [0.25404089 0.8209222  0.46288527 0.89299552]
 [0.16121709 0.66174634 0.99215048 0.95912954]
 [0.61961673 0.40424567 0.97597764 0.64643971]]


**Problem 1 (5 points)**

Write a function called **GetIndicesOfPath** that takes as input a 


- **path**, which is **list** of individual characters in the set {"H","V"} 

and outputs 

- a **list** of **2-tuples** giving the pairs of indices $(I,J)$ corresponding to positions in a matrix starting from $(0,0)$ and ending with $(m,n)$ where $m$ is the number of V's in the path, and $n$ is the number of H's in the path.

So for example, the path ['H','H','V','V','H'] should give as output the *list*
[(0,0),(0,1),(0,2),(1,2),(2,2),(2,3)]

In [34]:
# Code cell for Problem 1
def GetIndicesOfPath(path):
    i = 0
    j = 0
    tuple_i_j = [(i, j)]
    
    for character in path:
        if character == 'V':
            i += 1
            j = j
            tuple_i_j.append((i, j))
        elif character == 'H':
            i = i
            j += 1
            tuple_i_j.append((i, j))
    return tuple_i_j
    #print()

**Problem 2 (5 points)**

Write a function called **PathCost** that takes as inputs the following:

- two positive integers **m** and **n**, giving grid dimenssions, 
- a numpy array **H** ($(m+1) \times n$) giving, in position $(i,j)$ the cost of a horizontal move from $(i,j)$ to $(i,j+1),$ and
- a numpy array **V** ($m \times (n+1))$ giving, in postion $(i,j)$ the cost of a vertical move from $(i,j)$ to $(i+1,j)$
- a **path**, which is a list of characters of size $m+n$ consisting of $m$ V's and $n$ H's. 

and as output the cost of moving from $(0,0)$ to $(m,n)$ defined by the horizontal and vertical moves in path.


In [35]:
# Code cell for Problem 2
def PathCost(m,n,H,V,path): 
        
    start = (0, 0)
    count = 0
    (I, J) = start
    
    for character in path:
        if character == 'H':
            count += H[I][J]
            I = I
            J += 1
        elif character == 'V':
            count += V[I][J]
            I += 1
            J = J
    return count

**Problem 3 (5 points)**

Write a function called **LeastCostPathBruteForce** that takes as input

- two positive integers **m** and **n**, giving grid dimensions, 
- a numpy array **H** ($(m+1) \times n$) giving, in position $(i,j)$ the cost of a horizontal move from $(i,j)$ to $(i,j+1),$ and
- a numpy array **V** ($m \times (n+1))$ giving, in postion $(i,j)$ the cost of a vertical move from $(i,j)$ to $(i+1,j)$

and as output gives a **2-tuple** containing (in the following order):

- the **cost** (a number) of a least cost path from $(0,0)$ to $(m,n)$ **rounded to 3 decimal places,** and 

- an optimal path, which should be a **list of 2-tuples** [(0,0),....,(m,n)] giving nodes visited along an optimal path *in order*.

Your function should solve the problem using the **brute-force** approach of iterating over all possible paths.

It is always a good idea to test your code problems where a brute-force solution can be found. This code will not be useful practically for large values of $m$ and $n$ but you **can** use it for testing purposes. 

It would be wise to test your code on some small examples in a **different notebook**.

In [36]:
# Code cell for Problem 3
def LeastCostPathBruteForce(m,n,H,V):

    Vlist = ["V" for i in range(m)]
    Hlist = ["H" for i in range(n)]
    
    paths = multiset_permutations(Vlist + Hlist)
    
    path_tuple = []
    cost_tuple = np.inf
    
    
    for path in paths:
        
        cost = PathCost(m,n,H,V,path)
        cost_tuple = min(cost_tuple, cost)
        
        if cost_tuple == cost:
            path_tuple = GetIndicesOfPath(path)
        else:
            continue
            
    return round(cost_tuple, 3), path_tuple

**Problem 4 (2 points)**

Run the code in the following cell to determine the optimal cost and optimal path in the H1, V1 example. 

**You should not modify the cell - just run it.**

In [37]:
# Code cell for Problem 4
LeastCostPathBruteForce(4,3,H1,V1)

(2.4, [(0, 0), (1, 0), (2, 0), (3, 0), (3, 1), (3, 2), (4, 2), (4, 3)])

**Problem 5 (2 points)**

Run the code in the following cell to determine the optimal cost and optimal path in the H2, V2 example. 

**You should not modify the cell - just run it.**

In [38]:
# Code cell for Problem 5
LeastCostPathBruteForce(5,8,H2,V2)

(2.746,
 [(0, 0),
  (0, 1),
  (1, 1),
  (2, 1),
  (3, 1),
  (3, 2),
  (4, 2),
  (4, 3),
  (4, 4),
  (4, 5),
  (4, 6),
  (5, 6),
  (5, 7),
  (5, 8)])

**Problem 6 (21 points)**

Write code that takes the **same inputs** and gives the **same outputs** as in the **LeastCostPathBruteForce** function, but this time solving the problem using dynamic programming as described in the *LeastCostPathInRectangularGrid.pdf* document. Call this function **LeastCostPathDynamicProgramming**.

**Make sure** you round your least cost solution to 3 decimal places.

You should test your code in **a different notebook** on random cases when m and n are small enough so that the brute-force method can be applied and you should get the same answers using the two methods provided that there is no possibility of multiple optimal paths. (This will have a **very small probability** if you take V and H to be random with uniformly distributed entries.)

In [39]:
# Code cell for Problem 6
def LeastCostPathDynamicProgramming(m,n,H,V):
    
    
    C = np.zeros((m + 1, n + 1))
    #print(C)
    
    D = [[None for _ in range(n + 1)] for __ in range(m + 1)]
    #print(D)
    
    C[0][0] = 0
    
    #col
    for col in range(1, n + 1):
        C[0][col] = np.sum(H[0][:col])
        D[0][col] = 'H'
        
    #row
    for row in range(1, m + 1):
        C[row][0] = np.sum(np.transpose(H)[0][:row])
        D[row][0] = 'V'
        
    # C,D Matrix 
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            
            if C[i - 1][j] + V[i - 1][j] <= C[i][j - 1] + H[i][j - 1]:
                C[i][j] = C[i - 1][j] + V[i - 1][j]
                D[i][j] = 'V'
            
            else:
                C[i][j] = C[i][j - 1] + H[i][j - 1]
                D[i][j] = 'H'
    
    
    node_for_path = [(m, n)]
    
    while len(node_for_path) < m + n:
        (a, b) = node_for_path[-1]
        
        if D[a][b] == 'V':
            node_for_path.append((a - 1, b))
        
        elif D[a][b] == 'H':
            node_for_path.append((a, b - 1))

    node_for_path.reverse()
    
    return round(C[-1][-1], 3), node_for_path

**Problem 7 (2 points)**

Run the code in the following cell to determine the optimal cost and optimal path in the H1, V1 example. 

**You should not modify the cell - just run it.**

In [40]:
# Code cell for Problem 7
LeastCostPathDynamicProgramming(4,3,H1,V1)

(2.336, [(1, 0), (2, 0), (3, 0), (4, 0), (4, 1), (4, 2), (4, 3)])

**Problem 8 (2 points)**

Run the code in the following cell to determine the optimal cost and optimal path in the H2, V2 example. 

**You should not modify the cell - just run it.**

In [41]:
# Code cell for Problem 8
LeastCostPathDynamicProgramming(5,8,H2,V2)

(2.671,
 [(1, 0),
  (2, 0),
  (3, 0),
  (3, 1),
  (3, 2),
  (4, 2),
  (4, 3),
  (4, 4),
  (4, 5),
  (4, 6),
  (5, 6),
  (5, 7),
  (5, 8)])

**Problem 9 (2 points)**

Run the code in the following cell to determine the optimal cost and optimal path in the H3, V3 example. 

**You should not modify the cell - just run it.**

In [42]:
# Code cell for Problem 9
LeastCostPathDynamicProgramming(40,30,H3,V3)

(17.65,
 [(1, 0),
  (2, 0),
  (3, 0),
  (4, 0),
  (5, 0),
  (5, 1),
  (5, 2),
  (6, 2),
  (7, 2),
  (8, 2),
  (9, 2),
  (9, 3),
  (10, 3),
  (11, 3),
  (11, 4),
  (11, 5),
  (11, 6),
  (12, 6),
  (13, 6),
  (14, 6),
  (15, 6),
  (16, 6),
  (17, 6),
  (18, 6),
  (19, 6),
  (20, 6),
  (21, 6),
  (21, 7),
  (21, 8),
  (21, 9),
  (22, 9),
  (23, 9),
  (23, 10),
  (23, 11),
  (23, 12),
  (23, 13),
  (24, 13),
  (25, 13),
  (25, 14),
  (25, 15),
  (25, 16),
  (25, 17),
  (25, 18),
  (25, 19),
  (26, 19),
  (26, 20),
  (26, 21),
  (26, 22),
  (26, 23),
  (27, 23),
  (28, 23),
  (29, 23),
  (30, 23),
  (31, 23),
  (32, 23),
  (32, 24),
  (33, 24),
  (34, 24),
  (34, 25),
  (35, 25),
  (36, 25),
  (37, 25),
  (37, 26),
  (37, 27),
  (38, 27),
  (39, 27),
  (39, 28),
  (40, 28),
  (40, 29),
  (40, 30)])

**Problem 10 (2 points)**

Run the code in the following cell to determine the optimal cost in the H4, V4 example. 

**You should not modify the cell - just run it.**

In [43]:
# Code cell for Problem 10
LeastCostPathDynamicProgramming(400,300,H4,V4)[0]

168.077

**Problem 11 (2 points)**

Run the code in the following cell to determine the optimal cost in the H5, V5 example. 

**You should not modify the cell - just run it.**

In [44]:
# Code cell for Problem 11
LeastCostPathDynamicProgramming(800,1000,H5,V5)[0]

422.119

Make sure to 

- run all cells
- save your notebook 

before submitting it.